name: Runic formatting

on:
  pull_request:
    branches: [main]
    paths:
      - "**.jl"
      - ".github/workflows/runic.yaml"
  push:
    branches: [main]
    paths:
      - "**.jl"
      - ".github/workflows/runic.yaml"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  runic:
    name: Runic formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Set up Julia
        uses: julia-actions/setup-julia@v3
        with:
          version: "1.11"

      - uses: fredrikekre/runic-action@v1
        with:
          version: "1"
